modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "smallships"
version = "${version}"
displayName = "Small Ships"
authors = "talhanation, metroite"
updateJSONURL="https://raw.githubusercontent.com/talhanation/smallships/main/UpdateNeoForge.json"
description = '''
This mod adds vanilla friendly ships into Minecraft!
'''
logoFile = "icon.png"

[[dependencies.smallships]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smallships]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "smallships.mixins.json"

[[mixins]]
config = "smallships-common.mixins.json"

[[mixins]]
config = "smallships-fabric-neoforge.mixins.json"
